file=open("sample.txt","r")
content=file.readlines()
print(type(content))
print(content)
file.close()
file=open("sample.txt","w")
file.writelines("buy\n")
file.close()
file=open("sample.txt","a")
file.write("good by\n")
file.write("dasvedania\n")
